//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFIDIntegratedApplication.ServiceReference4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.IVitalSignsService")]
    public interface IVitalSignsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVitalSignsService/realtimeAnalyze", ReplyAction="http://tempuri.org/IVitalSignsService/realtimeAnalyzeResponse")]
        void realtimeAnalyze();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVitalSignsService/realtimeAnalyze", ReplyAction="http://tempuri.org/IVitalSignsService/realtimeAnalyzeResponse")]
        System.Threading.Tasks.Task realtimeAnalyzeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVitalSignsService/offlineAnalyze", ReplyAction="http://tempuri.org/IVitalSignsService/offlineAnalyzeResponse")]
        void offlineAnalyze(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVitalSignsService/offlineAnalyze", ReplyAction="http://tempuri.org/IVitalSignsService/offlineAnalyzeResponse")]
        System.Threading.Tasks.Task offlineAnalyzeAsync(string fileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVitalSignsServiceChannel : RFIDIntegratedApplication.ServiceReference4.IVitalSignsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VitalSignsServiceClient : System.ServiceModel.ClientBase<RFIDIntegratedApplication.ServiceReference4.IVitalSignsService>, RFIDIntegratedApplication.ServiceReference4.IVitalSignsService {
        
        public VitalSignsServiceClient() {
        }
        
        public VitalSignsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VitalSignsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VitalSignsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VitalSignsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void realtimeAnalyze() {
            base.Channel.realtimeAnalyze();
        }
        
        public System.Threading.Tasks.Task realtimeAnalyzeAsync() {
            return base.Channel.realtimeAnalyzeAsync();
        }
        
        public void offlineAnalyze(string fileName) {
            base.Channel.offlineAnalyze(fileName);
        }
        
        public System.Threading.Tasks.Task offlineAnalyzeAsync(string fileName) {
            return base.Channel.offlineAnalyzeAsync(fileName);
        }
    }
}
